version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      quality-toolchain:
        patterns:
          - c8
          - eslint
          - knip
          - lint-staged
          - markdown-link-check
          - markdownlint-cli2
          - prettier
          - publint
          - typescript
          - typescript-eslint
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
